app/Http/routes.php
<?php
ini_set('xdebug.max_nesting_level', 120);

Route::get('500', function()
{
    return 'ww';
});


if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}


/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () {
    return redirect('Dashboard');
});




use App\User;
 Route::get('users',function(){
 	return view('test')->with('users',User::paginate(5));
 });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    //load Auth 
    Route::auth();
    //Dashboard all
        //
        Route::resource('Dashboard',        'DashboardController');
    //User      admin
        Route::group(['middleware' => 'role:admin || Sadmin || vodadmin'], function () {
                Route::resource('User',        'Auth\UserController');
                                Route::get('uploadUser',         array('as'=>'User.upload'  ,'uses'=>'Auth\UserController@upload'));
               Route::post('uploadUser',         array('as'=>'User.uploaded','uses'=>'Auth\UserController@uploaded'));
        });
    //Headcount admin || qmanger || qsuper
        Route::group(['middleware' => 'role:admin || qmanger || qsuperqobserver || Sadmin || vodadmin' ], function () {
            Route::resource('Project',          'Headcount\ProjectController');
            Route::resource('Manager',          'Headcount\ManagerController');
            Route::resource('Supervisor',       'Headcount\SupervisorController');
            Route::resource('Teamleader',       'Headcount\TeamleaderController');
            Route::resource('Senior',           'Headcount\SeniorController');
            Route::resource('Agent',            'Headcount\AgentController');
            Route::get('uploadAgent',         array('as'=>'Agent.upload'  ,'uses'=>'Headcount\AgentController@upload'));
            Route::post('uploadAgent',        array('as'=>'Agent.uploaded','uses'=>'Headcount\AgentController@uploaded'));
        });
    //Seeting   admin || qmanger || qsuper
        Route::group(['middleware' => 'role:admin || qmanger || qsuper || Sadmin || vodadmin'], function () {
            Route::resource('Location',         'Seeting\LocationController');
            Route::resource('Department',       'Seeting\DepartmentController');
            Route::resource('Deduction',        'Seeting\DeductionController');
            Route::resource('AttributeOption',  'Seeting\AttributeOptionController');
            Route::resource('Attribute',        'Seeting\AttributeController');
            Route::resource('Section',          'Seeting\SectionController');
            Route::resource('Category',         'Seeting\CategoryController');
            Route::resource('ScoreSheet',       'Seeting\ScoreSheetController');
        });
    //Monitor   admin || qmanger || qsupers
        Route::group(['middleware' => 'role:admin || qmanger || oleader || qsuper || qobserver || qspecia || qobserver || oagent || Sadmin || vodadmin'], function () {
            Route::resource('Monitor',          'Quality\MonitorController');
            Route::resource('Coaching',         'Quality\CoachingController');
            Route::get('CloseCoaching',     array('as'=>'Coaching.close','uses'=>'Quality\CoachingController@close'));
            Route::resource('Additional',       'Quality\AdditionalController');
            Route::get('CloseAdditional',   array('as'=>'Additional.close','uses'=>'Quality\AdditionalController@close'));
        });
    //Ajax Controllers
        Route::post('divajax'   , array('as'=>'divajax','uses'=>'AjaxController@divajax'));
        Route::get('Ajaxrelationlist'   , array('as'=>'Ajaxrelationlist','uses'=>'AjaxController@Ajaxrelationlist'));
        Route::get('AjaxDropDownList',  array('as'=>'Ajax.AjaxDropDownList','uses'=>'AjaxController@DropDownList'));
        Route::get('AjaxDropDown',      array('as'=>'Ajax.AjaxDropDown','uses'=>'AjaxController@DropDown'));
        Route::get('AjaxVildation',     array('as'=>'Ajax.AjaxVildation','uses'=>'AjaxController@AjaxVildation'));
        Route::get('AjaxScoreSheet',    array('as'=>'Ajax.AjaxScoreSheet','uses'=>'AjaxController@AjaxScoreSheet'));
        Route::get('Ajaxtable',         array('as'=>'Ajax.Ajaxtable','uses'=>'AjaxController@Ajaxtable'));
        Route::post('Ajaxrow',          array('as'=>'Ajax.Ajaxrow','uses'=>'AjaxController@Ajaxrow'));
        Route::get('ADDLF',             array('as'=>'Ajax.ADDLF','uses'=>'AjaxController@ADDLF'));
                    Route::get('/searches',             array('as'=>'Monitor.test','uses'=>'Quality\MonitorController@test'));
            Route::get('serach/{id}{search}','Quality\MonitorController@serach');
    //Report   admin || qmanger || qsuper
        Route::group(['middleware' => 'role:admin || qmanger || qsuper || oleader || osuper|| omanger || qspecia || qobserver || oagent || Sadmin || training || vodadmin'], function () {
                Route::resource('Report',           'Report\ReportController');
                 Route::resource('Vreport',          'Report\VReportController');
        });

    
    
    



});

app/Http/Controllers/Report/ReportController - Copy.php
<?php

namespace App\Http\Controllers\Report;
use Illuminate\Http\Request;
use Auth;
use Validator;
use App\Report;
use DB;
use Excel;
use App\Http\Controllers\Controller;


class ReportController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects   =  \App\Project::all();
        $supers     =  \App\Supervisor::all();
        $teamleaders=  \App\Teamleader::all();
        $agents     =  \App\Agent::all();
        $user       =  \App\User::all();
        $monitortype= array(''=>'Select','Standard'=>'Standard','additional'=>'additional');
        $observetype= array(''=>'Select','Remotely'=>'Remotely','Side-by-Side'=>'Side-by-Side');
        $array      = array(''=>'Select an option','projects'=>'project','users'=>'Consistancy','departments' => 'Analysis','employees' =>'agent');
        return view('Report.Report.index',compact('array','projects','supers','teamleaders','agents','user','monitortype','observetype'));

        
        



    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        //
    }

    /**
     * Quality a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // virable
            $sheetName      = $request->TypeOfReport;
            $seach          = $request->searchvalue;
            $from           = $request->startdate;
            $to             = $request->enddate;

        if($sheetName == 'project'){
            return $this->ProjectReport($sheetName,$seach,$from,$to);
        }elseif ($sheetName == 'Consistancy') {
            return $this->ConsistancyReport($sheetName,$seach,$from,$to);
        }elseif ($sheetName == 'Analysis') {
            return $this->AnalysisReport($sheetName,$seach,$from,$to);
        }elseif ($sheetName == 'agent') {
            return $this->AgentReport($sheetName,$seach,$from,$to);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        //
        $Modal      ='\App\\'.$request->TypeOfReport;
        $myModal    = new $Modal;  
        $DataTable  = $Modal::orderBy('id','desc')->paginate(10);
        return view('Report.Report.table',compact('myModal','DataTable'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        
    }
    //Done
        function ProjectReport($sheetName,$seach,$from,$to){
            $data   = Report::where('monitors.project_id',$seach)
                    ->join('projects','projects.id','=','monitors.project_id')
                    ->join('agents','agents.id','=','agent_id')
                    ->select('projects.name as Project','agents.name as Agent')
                    ->selectRaw('count(monitors.id) as  "# of Std Call"')
                    ->selectRaw('SEC_TO_TIME(SUM(call_duration)) as  "Total Calls Duration"')
                    ->selectRaw('SEC_TO_TIME(SUM(hold_duration)) as  "Total Hold Duration"')
                    ->selectRaw('SUM(bce) as "# of BCE"')
                    ->selectRaw('SUM(ece) as "# of ECE"')
                    ->selectRaw('SUM(nce) as "# of NCE"')
                    ->selectRaw('CONCAT(ROUND((SUM(total_score) / count(total_score)),2)," %") as "Score Of agents"')
                    ->selectRaw('COUNT(CASE WHEN bce > 0 THEN 1 END) AS "Accuracy of BCE"')
                    ->selectRaw('COUNT(CASE WHEN ece > 0 THEN 1 END) AS "Accuracy of ECE"')                
                    ->selectRaw('COUNT(CASE WHEN bce > 0 THEN 1 END)  + COUNT(CASE WHEN ece > 0 THEN 1 END) AS "% of HPD"')
                    ->selectRaw('COUNT(CASE WHEN nce > 0 THEN 1 END) AS "Accuracy of NCE"')
                    ->whereBetween('monitors.created_at', [$from, $to])
                    ->orderBy('monitors.id','desc')
                    ->groupBy('agents.id')
                    ->get();
            $total  = Report::where('monitors.project_id',$seach)
                    ->join('projects','projects.id','=','monitors.project_id')
                    ->join('agents','agents.id','=','agent_id')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A1')
                    ->selectRaw('Concat(SUBSTRING(1,0), "Total #") AS Total')
                    ->selectRaw('count(monitors.id) as  "# of Std Call"')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A2')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A3')
                    ->selectRaw('SUM(bce) as "# of BCE"')
                    ->selectRaw('SUM(ece) as "# of ECE"')
                    ->selectRaw('SUM(nce) as "# of NCE"')
                    ->selectRaw('CONCAT(ROUND((SUM(total_score) / count(total_score)),2)," %") as "Score Of agents"')
                    ->selectRaw('COUNT(CASE WHEN bce > 0 THEN 1 END) AS "Accuracy of BCE"')
                    ->selectRaw('COUNT(CASE WHEN ece > 0 THEN 1 END) AS "Accuracy of ECE"')
                    ->selectRaw('COUNT(CASE WHEN bce > 0 THEN 1 END) + COUNT(CASE WHEN ece > 0 THEN 1 END) AS "% of HPD"')                    
                    ->selectRaw('COUNT(CASE WHEN nce > 0 THEN 1 END) AS "Accuracy of NCE"')
                    ->whereBetween('monitors.created_at', [$from, $to])
                    ->orderBy('monitors.id','desc')
                    ->get();
            $Percent= Report::where('monitors.project_id',$seach)
                    ->join('projects','projects.id','=','monitors.project_id')
                    ->join('agents','agents.id','=','agent_id')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A1')
                    ->selectRaw('Concat(SUBSTRING(1,0), "Total %") AS Total')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A2')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A3')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A4')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A5')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A6')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A7')
                    ->selectRaw('Concat(SUBSTRING(1,0), " ") as A8')
                    ->selectRaw('Concat(ROUND(100-( COUNT(CASE WHEN bce > 0 THEN 1 END) / count(monitors.id))*100,2)," %")  as "#BCE"')
                    ->selectRaw('Concat(ROUND(100-( COUNT(CASE WHEN ece > 0 THEN 1 END) / count(monitors.id))*100,2)," %")  as "#ECE"')
                    ->selectRaw('Concat(ROUND(((COUNT(CASE WHEN bce > 0 THEN 1 END)+ COUNT(CASE WHEN ece > 0 THEN 1 END)) / count(monitors.id))*100,2)," %")  as "#HPD"')
                    ->selectRaw('Concat(ROUND(100-( COUNT(CASE WHEN nce > 0 THEN 1 END) / count(monitors.id))*100,2)," %")  as "#NCE"')
                    ->whereBetween('monitors.created_at', [$from, $to])
                    ->orderBy('monitors.id','desc')
                    ->get();                    
            Excel::create($sheetName.'_'.$seach, function($excel) use($data,$total,$Percent)
            {
                $excel->sheet('Sheet1', function($sheet) use($data,$total,$Percent) 
                {
                    $sheet->cells('A1:M1', function($cells) {
                        // manipulate the cell
                        $cells->setBorder('solid', 'solid', 'solid', 'solid');
                        $cells->setBackground('#2f75b5');
                        $cells->setFontColor('#ffffff');
                    });
                    $sheet->setColumnFormat(array(
                        'I' => '0%',
                    ));
                    
                    $sheet->setAutoFilter();
                    $sheet->fromArray($data);
                    $sheet->fromArray($total, null, 'A1', false, false);
                    $sheet->fromArray($Percent, null, 'A1', false, false);
                });
            })->export('xls');
        }

        function ConsistancyReport($sheetName,$seach,$from,$to){


            $data  = Report::whereBetween('monitors.created_at', [$from, $to])
                ->join('users','users.id','=','monitors.created_by')
                ->select('users.name as Observer')
                ->selectRaw('count(monitors.id) as  "# of Std Call"')
                ->selectRaw('SUM(bce) as "# of BCE"')
                ->selectRaw('SUM(ece) as "# of ECE"')
                ->selectRaw('SUM(nce) as "# of NCE"')
                ->selectRaw('CONCAT(ROUND((SUM(bce) / count(monitors.id)),2) * 100," %") as "% of BCE"')
                ->selectRaw('CONCAT(ROUND((SUM(ece) / count(monitors.id)),2) * 100," %") as "% of ECE"')
                ->selectRaw('CONCAT(ROUND((SUM(nce) / count(monitors.id)),2) * 100," %") as "% of NCE"')
                ->groupBy('monitors.created_by')
                ->get();

            Excel::create($sheetName.'_'.$seach, function($excel) use($data)
            {

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers\Quality;

use Illuminate\Http\Request;

use App\Http\Requests;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return "welcome";
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Report/Vreport/anlyisreport.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
    table{
        width:100%; 
        border-collapse:collapse; 
    }
    /* provide some minimal visual accomodation for IE8 and below */
    table th{
    background:#366092;
    color: #FFFFFF;
    }

    /*  Define the background color for all the ODD background rows  */
    table td:nth-child(odd){ 
        background:#CCCCCC;
    }
    /*  Define the background color for all the EVEN background rows  */
    table td:nth-child(even){
        background:#FFFFFF;
    }
</style>
</head>

<body>
<?php
echo '<table border="1">';
echo '<theader><tr>';
echo '<th rowspan="3">projects</th>';
        echo '<th rowspan="3">Agent</th>';
        echo '<th rowspan="3"># of Std Call</th>';
        echo '<th rowspan="3">Total Calls Duration</th>';
        echo '<th rowspan="3">Total Hold Duration</th>';
        echo '<th rowspan="3"># of BCE</th>';
        echo '<th rowspan="3"># of ECE</th>';
        echo '<th rowspan="3"># of NCE</th>';
        echo '<th rowspan="3">Score Of agentsr</th>';
        echo '<th rowspan="3">Accuracy of BCE</th>';
        echo '<th rowspan="3">Accuracy of ECE</th>';
        echo '<th rowspan="3">% of HPD</th>';
        echo '<th rowspan="3">Accuracy of NCE</th>';
         echo '</tr><tr>';
         echo '</tr><tr>';
        echo '</tr></theader>';  

        echo '<br>'; 
        echo '<tboody><tr>';

        foreach ($data  as $key => $value) {
            echo '<td>'.$value->Project.'</td>';
            echo '<td>'.$value->Agent.'</td>';
            echo '<td>'.$value->stdcalls.'</td>';
            echo '<td>'.$value->TotalCallsDuration.'</td>';
            echo '<td>'.$value->TotalHoldDuration.'</td>';
            echo '<td>'.$value->ofBCE.'</td>';
            echo '<td>'.$value->ofECE.'</td>';
            echo '<td>'.$value->ofNCE.'</td>';
            echo '<td>'.$value->ScoreOfagents.'</td>';
            echo '<td>'.$value->AccuracyofBCE.'</td>';
            echo '<td>'.$value->AccuracyofECE.'</td>';
            echo '<td>'.$value->ofHPD.'</td>';
            echo '<td>'.$value->AccuracyofNCE.'</td>';


                
         echo "</tr></tboody>";
        }

       

echo '</table>';
header('Content-type: application/vnd.ms-excel');
//header("Content-Disposition: attachment; filename='Analysis.xls'");
//$objWriter->save('php://output'); 
?>
</body>
</html>

resources/views/Report/Vreport/index.blade.php
@extends('layouts.app')
@section('content')
<br/>
<div class="container-fluid">
	<!--Index-->
	<form action="{{URL::route('Vreport.store')}}" data-toggle="validator"  id='myForm' role="form" method="POST">
		{!! csrf_field() !!}
		<div class="col-md-8 col-md-push-2">
			<div class="panel panel-default">
				<!-- Default panel contents -->
				<div class="panel-heading">
					<div class="row">
						<div class="col-lg-6"><h5>Adherence Report</h5></div>
					</div>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-4">
					        <div class="form-group">
					            <div class='input-group date' id='startdate'>
					                <input type='text' class="form-control" name="startdate" required="required"/>
					                <span class="input-group-addon">
					                    <span class="glyphicon glyphicon-calendar"></span>
					                </span>
					            </div>
					        </div>
					    </div>
					    <div class="col-md-4">
					        <div class="form-group">
					            <div class='input-group date' id='enddate'>
					                <input type='text' class="form-control" name="enddate" required="required"/>
					                <span class="input-group-addon">
					                    <span class="glyphicon glyphicon-calendar"></span>
					                </span>
					            </div>
					        </div>
					    </div>
			        	<div class="col-md-4">
			        		<div class="form-group">
				                <select name="TypeOfReport" id="TypeOfReport" class="form-control" required="required">  <!-- onchange="DropDown('TypeOfReport','searchvalue')" -->
				                    @role('osuper | oleader | osenior | oagent')
				                	@foreach($array as $key => $value)
				                	 @if($value == 'project')
										<option id="{{$key}}">{{$value}}</option>
									 @endif	
									@endforeach
                                     @endrole

                                     @role('admin | qmanger | qsuper | qspecia | qobserver')
				                	<option></option>
				                	@foreach($array as $key => $value)
										<option id="{{$key}}">{{$value}}</option>
									@endforeach
                                    @endrole

				                </select>
					        </div>
			        	</div>
			        </div>
			        <div class="row">
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="project">project</label>
				                <select name="project" id="project" class="form-control">
				                	<option></option>
				                	@foreach($projects as $value)
										<option value="{{$value->id}}">{{$value->name}}</option>
									@endforeach
				                </select>
					        </div>
			        	</div>
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="super">super</label>
				                <select name="super" id="super" class="form-control">
				                	<option></option>
				                	@foreach($supers as $value)
										<option value="{{$value->id}}">{{$value->name}}</option>
									@endforeach
				                </select>
					        </div>
			        	</div>
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="leader">leader</label>
				                <select name="leader" id="leader" class="form-control" >
				                	<option></option>
				                	@foreach($teamleaders as $value)
										<option value="{{$value->id}}">{{$value->name}}</option>
									@endforeach
				                </select>
					        </div>
					    </div>
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="agent">agent</label>
				                <select name="agent" id="agent" class="form-control" >
				                	<option></option>
				                	@foreach($agents as $value)
										<option value="{{$value->id}}">{{$value->name}}</option>
									@endforeach
				                </select>
					        </div>
			        	</div>
					</div>
					@role('admin || qmanger || qsuper')
					<div class="row">
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="observers">observers</label>
				                <select name="observers" id="observers" class="form-control">
				                	<option></option>
				                	@foreach($user as $value)
										<option value="{{$value->id}}">{{$value->name}}</option>
									@endforeach
				                </select>
					        </div>
			        	</div>
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="monitoring">monitoring type</label>
				                <select name="monitoring" id="monitoring" class="form-control" >
				                	<option></option>
				                	@foreach($monitortype as $key => $value)
										<option id="{{$key}}">{{$value}}</option>
									@endforeach
				                </select>
					        </div>
			        	</div>
			        	<div class="col-md-3">
			        		<div class="form-group">
			        			<label for="observing">observing call</label>
				                <select name="observing" id="observing" class="form-control">
				                	<option></option>
				                	@foreach($observetype as $key => $value)
										<option id="{{$key}}">{{$value}}</option>
									@endforeach
				                </select>
					        </div>
					    </div>
					</div>
					@endrole
				</div>
				<div class="panel-footer text-right">
					<button type="submit" class="btn btn-primary">View Report</button>

					
				</div>
			</div>
		</div>	
	</form>
	
	<!--End Index-->
</div>

<script type="text/javascript">
    $(function () {
        $('#startdate').datetimepicker({
        	format: 'YYYY-MM-DD HH:mm:ss',
        	defaultDate: ' {{date("Y-m-d")}} 00:00:00'
        });
        $('#enddate').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            defaultDate: ' {{date("Y-m-d")}} 23:59:59',
            useCurrent: false //Important! See issue #1075
        });
        $("#startdate").on("dp.change", function (e) {
            $('#enddate').data("DateTimePicker").minDate(e.date);
        });
        $("#enddate").on("dp.change", function (e) {
            $('#startdate').data("DateTimePicker").maxDate(e.date);
        });
    });

    $('#TypeOfReport').change(function () 
	{
		var val = $(this).val();
		switch (val) 
		{
			case "":
			case "project":
			case "Consistancy":
			case "agent":
			case "Repaeted fail":
				document.getElementById("project").required = false;
			break;
			case "Analysis":
				document.getElementById("project").required = true;
			break;
			case "Non critical":
				document.getElementById("project").required = true;
			break;
		}
	});
    // function DropDown(name,appendtolist) {
    //     //var table = $('#'+name+' :selected').val();
    //     var table = $('#'+name+' :selected').attr( "id" );
    //     //remove _i from value
    //     $.ajax({
    //             url     :"{{url('AjaxDropDown?')}}",
    //             data    :{table:table,appendtolist:appendtolist},
    //             dataType:'json',
    //             type    :'get',
    //             success : function(data){
    //                 //$('.classComplaint').html(data);
    //                 //alert(appendtolist);
    //                 var $option = $('#'+appendtolist);
    //                 $option.empty();
    //                 $option.append('<option value="" selected>Select</option>');
    //                 $.each(data, function(index, value) {
                        
    //                     $option.append('<option value="'+value.id+'" id="'+value.id+'">'+value.name+'</option>');
    //                 });
    //                 $('#'+appendtolist).trigger('chosen:updated');
    //             }
    //     });
    //     return false;
    // };
</script>
@endsection

resources/views/Report/Vreport/table.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid ">
	
	<!--Index-->
	<input type="hidden" id="key" 	 	 value="id">
	<input type="hidden" id="model"  	 value="Report">
	<input type="hidden" id="groupby" 	 value="id">
	<input type="hidden" id="path" 	 	 value="Quality">
	<input type="hidden" id="conditions" value='{}' name="conditions"  >
 	@include('layouts.table')

	<!--End Index-->
</div>
<script type="text/javascript">
	$('.col-int').remove();
</script>
@endsection